quarkus:
  log:
    console:
      filter: qr-filter
    level: TRACE
  http:
    cors:
      ~: true
      origins: /.*/
      methods: GET,PUT,POST,DELETE
      access-control-allow-credentials: true
    access-log:
      enabled: true
  datasource:
    db-kind: postgresql
    username: root
    password: root
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/cokie
  hibernate-orm:
    database:
      generation: update
mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem