version: "3.4"

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/java:1-17-bullseye
    volumes:
      - ../..:/workspaces
  minio:
    image: minio/minio
    volumes:
      - minio-data:/tokisaki
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9111:9001"
    command: server --console-address ':9001' /tokisaki
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: Tokisaki
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  minio-data:
  redis-data: