quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: root
    reactive:
      url: vertx-reactive:postgresql://host.docker.internal:5432/Tokisaki
  hibernate-orm:
    database:
      generation: none
  redis:
    hosts: redis://host.docker.internal:6379
  minio:
    url: http://host.docker.internal:9000
    access-key: minioadmin
    secret-key: minioadmin