quarkus:
  profile: dev
  package:
  #    type: uber-jar # 打包über-jar
  #    type: legacy-jar # 打包legacy-jar
  banner:
    path: tokisaki.txt
  application:
    name: tokisaki
  log:
    level: INFO
  http:
    cors:
      ~: true
      origins: /.*/
      methods: GET,PUT,POST,DELETE
      access-control-allow-credentials: true
  rest-client:
    midjourney:
      read-timeout: 900000
    chat:
      read-timeout: 900000
    xyz:
      follow-redirects: true
  cache:
    redis:
      robot:
        expire-after-write: 1m
smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem
mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
  messaging:
    incoming:
      robot-login-success:
        connector: smallrye-rabbitmq
        routing-keys: robot.login.success
        queue:
          name: queue.robot.login.success
        exchange:
          name: exchange.qq.robot
      robot-state-change:
        connector: smallrye-rabbitmq
        routing-keys: robot.state.change
        queue:
          name: queue.robot.state.change
        exchange:
          name: exchange.robot
    outgoing:
      robot:
        connector: smallrye-rabbitmq
        exchange:
          name: exchange.robot
      qq-robot:
        connector: smallrye-rabbitmq
        exchange:
          name: exchange.qq.robot