quarkus:
  http:
    access-log:
      enabled: true
  datasource:
    db-kind: postgresql
    username: postgres
    password: root
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/Tokisaki
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
  redis:
    hosts: redis://localhost:6379
  minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
rabbitmq-host: localhost
rabbitmq-port: 5672
rabbitmq-username: tokisaki
rabbitmq-password: 123456
mp:
  messaging:
    incoming:
      robot-login-success:
        connector: smallrye-rabbitmq
        routing-keys: robot.login.success
        queue:
          name: robot-login-success
    outgoing:
      robot-login:
        connector: smallrye-rabbitmq
        default-roting-key: robot.login.*
        exchange:
          name: robot-login