quarkus:
  banner:
    path: tokisaki.txt
  log:
    level: INFO
    min-level: TRACE
#    category:
#      "org.hibernate.orm.jdbc.bind":
#        level: TRACE
  http:
    cors:
      ~: true
      origins: /.*/
      methods: GET,PUT,POST,DELETE
      access-control-allow-credentials: true
    access-log:
      enabled: true
  datasource:
    db-kind: postgresql
    username: postgres
    password: root
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/Tokisaki
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
  redis:
    hosts: redis://localhost:6379
  minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem
mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
