quarkus:
  profile: dev
  package:
    type: uber-jar # 打包über-jar
  #    type: legacy-jar # 打包legacy-jar
  banner:
    path: tokisaki.txt
  application:
    name: tokisaki
  log:
    level: INFO
  http:
    cors:
      ~: true
      origins: /.*/
      methods: GET,PUT,POST,DELETE
      access-control-allow-credentials: true
  rest-client:
    midjourney:
      read-timeout: 900000
    chat:
      read-timeout: 900000
    xyz:
      follow-redirects: true
smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem
mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem